version: "3.8"

services:
  flask_website:
    build:
      context: .
      dockerfile: Flask.Dockerfile
    container_name: flask-container
    expose:
      - "5005"
    ports:
      - "5005:5005"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - flask_website
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  app-network:
    driver: bridge